### ISSUE TITLE
Rename the repository and internal references into "eopkg"

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/eopkg#19]
The repository name is "package-management". The internal references are "pisi", given eopkg is a fork of pisi. This is confusing IMO. I'd like to rename everything into "eopkg" since that's how we've always called our package manager.

If you think backward reference matters, we can fork this very repository and call the new repo "eopkg", while archiving this one once the Python 3 port is over.

@GZGavinZhao @silkeh thoughts? This is low priority anyway.

**Comment by silkeh** [comment]
Yes, rename it!

**Comment by silkeh** [comment]
I renamed the repo, let's see if things break :sweat_smile:

**Comment by ermo** [comment]
@silkeh If this hasn't broken yet, please close it at your earliest convenience?
