### ISSUE TITLE
Compile py3 version of eopkg with nuitka compiler

### ISSUE THREAD

**Issue by ermo** [getsolus/eopkg#29]
To enable easy updates and rescue of existing installs, @ReillyBrogan suggested that we attempt to build and distribute our python3 port of eopkg as a single binary compiled with [nuitka](https://nuitka.net/doc/user-manual.html#use-case-1-program-compilation-with-all-modules-embedded), using the current system python3 package (3.10 as of this writing).

This issue is a tracker issue for that process, including describing how we plan to handle the situation where we have a system python3 update.

Related 

- [x] https://github.com/getsolus/packages/pull/1305

**Comment by ReillyBrogan** [comment]
We need to track all the python libs that eopkg uses and ensure that the eopkg package gets a relbump after every one of those is updated.

**Comment by GZGavinZhao** [comment]
Note to self: `eopkg rdb` failing with `db type is dbm.gnu, but the module is not available` can be fixed by appending `--include-module=dbm.gnu` when compiling with Nuitka.
