### ISSUE TITLE
python3: eopkg info -f regression

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/eopkg#40]
If you just run eopkg info somepkg then it'll you the "Installed Version" as well as "Package found in Solus Repository".

However, if you pass -f to info to show installed files it'll no longer show you the "Installed Version".

**Comment by sheepman4267** [comment]
This happens on py2 eopkg as well. Are we sure it's a problem?

**Comment by TraceyC77** [comment]
I can confirm that the output from eopkg and eopkg4-bin is identical, so this is not a regression.
The help output only promises it will show package files, not installed state.

**Comment by sheepman4267** [comment]
I feel like the bug might be that it *does* show the "package found in repository" bit.
