### ISSUE TITLE
bad parsing of non-ascii characters

### ISSUE THREAD

**Issue by davidjharder** [getsolus/eopkg#52]
Discovered here https://github.com/getsolus/packages/pull/2196

The package.yaml description, which includes some non-ascii characters, gives a garbled output is the pspec.xml. From the `polylith` package:

package.yml line:
```
    The poly tool helps you manage your polylith projects which introduces the architectural concept of “service level building blocks” which can be combined like LEGO® bricks to build our services and systems.
```

pspec.xml out:
```
<Description xml:lang="en">The poly tool helps you manage your polylith projects which introduces the architectural concept of &#x201c;service level building blocks&#x201d; which can be combined like LEGO&#xae; bricks to build our services and systems.
```

**Comment by ermo** [comment]
In my view, we need to consider how we can put in place measures that explicitly allow unicode (encoded as utf-8?) in the entire Solus tooling pipeline, but in ways which do not open us up to unpleasant attack vectors.

**Comment by ermo** [comment]
Just for context, in a hypothetical py3 eopkg, this is trivially worked around by decoding the html-encoded characters like so:

```
$ python3
Python 3.11.9 (main, Apr 12 2024, 19:58:05) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html
>>> html.unescape("Fast: it&apos;s fast &#x2013; really really fast!")
"Fast: it's fast – really really fast!"
```
